[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
cache_path = 'forge-cache'
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20000
test = 'test'
solc = '0.8.26'
fs_permissions = [
    { access = 'read-write', path = './deploy-out' },
    { access = 'read', path = './out' },
]
##### Uncomment if running storage layout verification
# ffi = true
# ast = true
# build_info = true
extra_output = ["storageLayout"]
evm_version = "cancun"

[rpc_endpoints]
story = "${STORY_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
