name: Foundry CI

on:
  pull_request:
    types: [closed]  # This will trigger when PRs are closed (including merges)

permissions:
  pull-requests: read
  contents: read

env:
  SAFE_MULTISIG_PROPOSER_ADDRESS: ${{ secrets.SAFE_MULTISIG_PROPOSER_ADDRESS }}
  SAFE_MULTISIG_PROPOSER_PRIVATE_KEY: ${{ secrets.SAFE_MULTISIG_PROPOSER_PRIVATE_KEY }}
  SAFE_MULTISIG_MAINNET_ADDRESS: ${{ secrets.SAFE_MULTISIG_MAINNET_ADDRESS }}
  SAFE_MULTISIG_AENEID_ADDRESS: ${{ secrets.SAFE_MULTISIG_AENEID_ADDRESS }}
  GH_TOKEN: ${{ github.token }}

jobs:

  # Add a timestamp to the build
  Timestamp:
    uses: storyprotocol/gha-workflows/.github/workflows/reusable-timestamp.yml@main

  foundry-test:
    strategy:
      fail-fast: true
    name: Run script
    runs-on: ubuntu-latest
    needs: [Timestamp]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Extract rpc url
        id: url
        run: |
          RPC_URL=$(gh pr view ${{ github.event.pull_request.number }} --json body -q '.body' | grep -oP 'rpc:\s*\K[^\s]+' || echo "")
          if [ -z "$RPC_URL" ]; then
            echo "No rpc url found in PR description. Please add 'rpc: <url>' to the PR description."
            exit 1
          fi
          echo "url=$RPC_URL" >> $GITHUB_OUTPUT

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build

      - name: Check PR conditions
        id: check_pr
        run: |
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]] || [[ "${{ github.event.pull_request.title }}" =~ ^upgrade-v ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

      - name: Run safe propose script 
        if: ${{ steps.check_pr.outputs.should_run }} == 'true'
        run: |
          npx hardhat safe-propose --chainid 1315 --operation schedule --previousversion 1.5.0 --newversion 1.5.1 --safeproposeraddress ${{ env.SAFE_MULTISIG_PROPOSER_ADDRESS }} --safeproposerprivatekey ${{ env.SAFE_MULTISIG_PROPOSER_PRIVATE_KEY }} --safemultisigaddressmainnet ${{ env.SAFE_MULTISIG_MAINNET_ADDRESS }} --safemultisigaddressaeneid ${{ env.SAFE_MULTISIG_AENEID_ADDRESS }}
